### ISSUE TITLE
Java Compiler Not Found Exception on Rule Insert

### ISSUE THREAD

**Issue by FlorianPatzerFraunhoferIOSB** [khaller93/graphdb-free#1]
When trying to submit any falid rule via GraphDB-Sparql-Editor, e.g.
```
prefix sys: <http://www.ontotext.com/owlim/system#>
INSERT DATA {
    <_:custom> sys:addRuleset
        '''Prefices {
				rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
			}
           Axioms {}
           Rules
           {
           	Id: firstRule
           		e	a	c
            	-------------------------------
				e <rdf:type> c
           }'''
}
```
GraphDB throws a `Compiler not found` exception.

The below stack trace from the graphdb error logs suggests that this Exception is thrown when committing a rule via rdf4j SAIL.

This does not happen in on the GraphDB-Free version 10.0.0 when run without docker, but only using this docker image (tested with image versions 9.11.0 and 10.0.0).
Any idea why this happens?

```
[ERROR] 2022-08-18 13:32:16,447 [repositories/repo | c.o.t.SailConnectionImpl] Transaction failed. Commit will be rolled back.
java.lang.RuntimeException: java.lang.RuntimeException: Java compiler not found!
        at com.ontotext.trree.SwitchableInferencer.addRuleset(SwitchableInferencer.java:216)
        at com.ontotext.trree.SwitchableInferencerTransactionState.addRuleset(SwitchableInferencerTransactionState.java:327)
        at com.ontotext.trree.SwitchableInferencerTransactionState.manipulateRuleset(SwitchableInferencerTransactionState.java:98)
        at com.ontotext.trree.SwitchableInferencerTransactionState.onCommitStart(SwitchableInferencerTransactionState.java:81)
        at com.ontotext.trree.SailConnectionImpl.doActualCommit(SailConnectionImpl.java:817)
        at com.ontotext.trree.SailConnectionImpl.flushInternal(SailConnectionImpl.java:1006)
        at com.ontotext.trree.SailConnectionImpl.flush(SailConnectionImpl.java:2880)
        at org.eclipse.rdf4j.repository.sail.SailRepositoryConnection.commit(SailRepositoryConnection.java:213)
        at com.ontotext.trree.monitorRepository.MonitorRepositoryConnection.commit(MonitorRepositoryConnection.java:302)
        at org.eclipse.rdf4j.repository.base.AbstractRepositoryConnection.conditionalCommit(AbstractRepositoryConnection.java:326)
        at com.ontotext.trree.monitorRepository.MonitorRepositoryConnection.access$100(MonitorRepositoryConnection.java:76)
        at com.ontotext.trree.monitorRepository.MonitorRepositoryConnection$1.execute(MonitorRepositoryConnection.java:466)
        at org.eclipse.rdf4j.http.server.repository.statements.StatementsController.getSparqlUpdateResult(StatementsController.java:257)
        at org.eclipse.rdf4j.http.server.repository.statements.StatementsController.handleRequestInternal(StatementsController.java:115)
        at com.ontotext.graphdb.sesame.StatementsController.handleRequestInternal(StatementsController.java:67)
        at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:177)
        at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:51)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:681)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)

...skipping 1 line
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at com.github.ziplet.filter.compression.CompressingFilter.doFilter(CompressingFilter.java:263)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at com.ontotext.forest.security.AdminDelegatingFilterProxy.doFilter(AdminDelegatingFilterProxy.java:84)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at com.ontotext.forest.clusterproxy.ClusterFilterBean.doFilter(ClusterFilterBean.java:70)
        at com.ontotext.forest.clusterproxy.ClusterLoadBalancerFilter.doFilterInternal(ClusterLoadBalancerFilter.java:28)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)

...skipping 1 line
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: Java compiler not found!
        at com.ontotext.trree.rules.RuntimeInferencerCompilerBase.compileSource(RuntimeInferencerCompilerBase.java:56)
        at com.ontotext.trree.SwitchableInferencer.addRuleset(SwitchableInferencer.java:214)
        ... 62 common frames omitted
[ERROR] 2022-08-18 13:32:16,552 [repositories/repo | c.o.f.s.GraphDBProtocolExceptionResolver] Error while handling request (500)
org.eclipse.rdf4j.http.server.ServerHTTPException: org.eclipse.rdf4j.repository.RepositoryException: org.eclipse.rdf4j.sail.SailException: java.lang.RuntimeException: java.lang.RuntimeException: Java compiler not found!
        at org.eclipse.rdf4j.http.server.repository.statements.StatementsController.getSparqlUpdateResult(StatementsController.java:269)
        at org.eclipse.rdf4j.http.server.repository.statements.StatementsController.handleRequestInternal(StatementsController.java:115)
        at com.ontotext.graphdb.sesame.StatementsController.handleRequestInternal(StatementsController.java:67)
        at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:177)
        at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:51)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:681)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at com.ontotext.forest.core.request.RequestFilter.doFilterInternal(RequestFilter.java:47)

...skipping 1 line
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at com.github.ziplet.filter.compression.CompressingFilter.doFilter(CompressingFilter.java:263)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at com.ontotext.forest.security.AdminDelegatingFilterProxy.doFilter(AdminDelegatingFilterProxy.java:84)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at com.ontotext.forest.clusterproxy.ClusterFilterBean.doFilter(ClusterFilterBean.java:70)
        at com.ontotext.forest.clusterproxy.ClusterLoadBalancerFilter.doFilterInternal(ClusterLoadBalancerFilter.java:28)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)

...skipping 1 line
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.eclipse.rdf4j.repository.RepositoryException: org.eclipse.rdf4j.sail.SailException: java.lang.RuntimeException: java.lang.RuntimeException: Java compiler not found!
        at org.eclipse.rdf4j.repository.sail.SailRepositoryConnection.commit(SailRepositoryConnection.java:217)
        at com.ontotext.trree.monitorRepository.MonitorRepositoryConnection.commit(MonitorRepositoryConnection.java:302)
        at org.eclipse.rdf4j.repository.base.AbstractRepositoryConnection.conditionalCommit(AbstractRepositoryConnection.java:326)
        at com.ontotext.trree.monitorRepository.MonitorRepositoryConnection.access$100(MonitorRepositoryConnection.java:76)
        at com.ontotext.trree.monitorRepository.MonitorRepositoryConnection$1.execute(MonitorRepositoryConnection.java:466)
        at org.eclipse.rdf4j.http.server.repository.statements.StatementsController.getSparqlUpdateResult(StatementsController.java:257)
        ... 50 common frames omitted
Caused by: org.eclipse.rdf4j.sail.SailException: java.lang.RuntimeException: java.lang.RuntimeException: Java compiler not found!
        at com.ontotext.trree.SailConnectionImpl.handleTransactionFailure(SailConnectionImpl.java:1479)
        at com.ontotext.trree.SailConnectionImpl$CommitContext.handleFailure(SailConnectionImpl.java:692)
        at com.ontotext.trree.SailConnectionImpl.flush(SailConnectionImpl.java:2883)
        at org.eclipse.rdf4j.repository.sail.SailRepositoryConnection.commit(SailRepositoryConnection.java:213)
        ... 55 common frames omitted
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Java compiler not found!
        at com.ontotext.trree.SwitchableInferencer.addRuleset(SwitchableInferencer.java:216)
        at com.ontotext.trree.SwitchableInferencerTransactionState.addRuleset(SwitchableInferencerTransactionState.java:327)
        at com.ontotext.trree.SwitchableInferencerTransactionState.manipulateRuleset(SwitchableInferencerTransactionState.java:98)
        at com.ontotext.trree.SwitchableInferencerTransactionState.onCommitStart(SwitchableInferencerTransactionState.java:81)
        at com.ontotext.trree.SailConnectionImpl.doActualCommit(SailConnectionImpl.java:817)
        at com.ontotext.trree.SailConnectionImpl.flushInternal(SailConnectionImpl.java:1006)
        at com.ontotext.trree.SailConnectionImpl.flush(SailConnectionImpl.java:2880)

...skipping 1 line
Caused by: java.lang.RuntimeException: Java compiler not found!
        at com.ontotext.trree.rules.RuntimeInferencerCompilerBase.compileSource(RuntimeInferencerCompilerBase.java:56)
        at com.ontotext.trree.SwitchableInferencer.addRuleset(SwitchableInferencer.java:214)
        ... 62 common frames omitted
```

**Comment by khaller93** [comment]
The Dockerfile is based on "jre-slim" to keep the image slim, and this version has no Java compiler included.

I will change it to the jdk version to support your use case of GraphDB.
